// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh6NgFzVO1Pp9yCF_SGgrDQJAqazoeBGw',
    appId: '1:842723396186:web:46294b834a6b479c68a663',
    messagingSenderId: '842723396186',
    projectId: 'fulltime-mtz',
    authDomain: 'fulltime-mtz.firebaseapp.com',
    storageBucket: 'fulltime-mtz.firebasestorage.app',
    measurementId: 'G-0FZTX6VXCN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0WiMM7jQdFL5FHIAZF6sQDAI6FzeAESk',
    appId: '1:842723396186:android:d0eac694f754155b68a663',
    messagingSenderId: '842723396186',
    projectId: 'fulltime-mtz',
    storageBucket: 'fulltime-mtz.firebasestorage.app',
  );
}
